tabWidth: 2
semi: false
singleQuote: true
trailingComma: "none"

plugins:
  - "@prettier/plugin-ruby"
  - "@4az/prettier-plugin-html-erb"
  - "prettier-plugin-tailwindcss"

rubyArrayLiteral: true
rubyHashLabel: true
rubyModifier: true
rubySingleQuote: true
rubyToProc: false

overrides:
  - files: '*.erb'
    options:
      parser: 'html'
  - files: "erb"
    options:
      parser: "html"
  - files: "*.html.erb"
    options:
      parser: "html"
