name: CD

on:
  push:
    branches:
      - main
      - dev

jobs:
  Deploy:
    if: ${{ github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/dev') }}
    runs-on: ubuntu-latest

    env:
      DOCKER_BUILDKIT: 1
      RAILS_ENV: production
      RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
      KAMAL_REGISTRY_PASSWORD: ${{ secrets.KAMAL_REGISTRY_PASSWORD }}
      KAMAL_REGISTRY_USERNAME: ${{ secrets.KAMAL_REGISTRY_USERNAME }}
      KAMAL_SERVICE_NAME: ${{ github.ref_name == 'main' && 'smart_edu' || 'smart_edu_dev'}}
      KAMAL_IMAGE_NAME: ${{github.ref == 'refs/heads/main' && 'c0ns03l/smartedu_a' || 'c0ns03l/smartedu_d'}}
      KAMAL_HOSTNAME: ${{github.ref == 'refs/heads/main' && 'aaa.buggycode.space' || 'dev.aaa.buggycode.space'}}
      VOLUME_PATH: ${{github.ref == 'refs/heads/main' && 'smart_edu_storage:/rails/storage' || 'smart_edu_storage_dev:/rails/storage'}}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.4.1
          bundler-cache: true

      - name: Install dependencies
        run: |
          gem install specific_install
          gem specific_install https://github.com/basecamp/kamal.git

      - uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Run deploy command
        run: kamal deploy
